[server]
host = "0.0.0.0"
port = 8000

[logging]
level = "INFO"
json = true
request_id_header = "X-Request-ID"

[database]
url = "postgresql+psycopg:
admin_url = "postgresql+psycopg:
pool_size = 10
max_overflow = 10
connect_timeout_s = 5

[providers]
default = "openai"
# concrete keys/urls provided via env in later steps

[security]
api_key_header = "X-Noosphera-API-Key"

[features]
auth_enabled = true   # switched to true in Step 1.3
