# FILE: noosphera/config/default.toml
[server]
host = "0.0.0.0"
port = 8000

[logging]
level = "INFO"
json = true
request_id_header = "X-Request-ID"

[database]
url = "postgresql+psycopg://app:app@localhost:5432/noosphera"
admin_url = "postgresql+psycopg://admin:admin@localhost:5432/noosphera"
pool_size = 10
max_overflow = 10
connect_timeout_s = 5

[providers]
default = "openai"
# concrete keys/urls provided via env in later steps

[security]
api_key_header = "X-Noosphera-API-Key"

[features]
auth_enabled = true   # switched to true in Step 1.3

# NEW (Step 1.4)
[chat]
history_max_messages = 20
mock_llm_enabled = true  # set false when real providers are wired (Step 1.5)
