# FILE: noosphera/config/default.toml
[server]
host = "0.0.0.0"
port = 8000

[logging]
level = "INFO"
json = true
request_id_header = "X-Request-ID"

[database]
url = "postgresql+psycopg://user:pass@localhost:5432/app"
admin_url = "postgresql+psycopg://admin:pass@localhost:5432/app"
pool_size = 10
max_overflow = 10
connect_timeout_s = 5

# NEW (Step 1.5) Provider defaults (disabled by default; override via env or config file)
[providers]
enabled = false
default_provider = "openai"
default_model = ""  # optional global fallback if per-provider not set

[providers.openai]
enabled = false
# IMPORTANT: never commit secrets; set via env: NOOSPHERA_PROVIDERS_OPENAI_API_KEY
api_key = ""
base_url = "https://api.openai.com/v1"
organization = ""
request_timeout_s = 60
default_model = ""   # e.g. "gpt-4o-mini" or "gpt-4.1-mini"

[providers.ollama]
enabled = false
host = "http://127.0.0.1:11434"
request_timeout_s = 60
default_model = ""   # e.g. "llama3.2:latest"

[security]
api_key_header = "X-Noosphera-API-Key"

[features]
auth_enabled = true   # switched to true in Step 1.3

# Step 1.4
[chat]
history_max_messages = 20
mock_llm_enabled = true  # set false when real providers are wired (Step 1.5)
